PublicBodyCategories.add(:es, [
"Poder Ejecutivo",
["presidencia","Presidencia y Org. Asociados", "una agencia de presidencia"],
["ministerio","Ministerios", "un ministerio"],
["direcciones", "Direcciones", "una direccion de ministerio"],
["museos", " Museos", "un museo"],
["embajadas", "Embajadas", "Una Embajada Uruguaya"],
["consulados", "Consulados", "Un Consulado Uruguayo"],
"Poder Legislativo",
["camara_de_senadores", "Camara de Senadores", "Una Camara del Legislativo"],
["camara_de_diputados", "Camara de Diputados", "Una Camara del Legislativo"],
["comision_administradora", "Comision Administradora","Una Comision Administradora del Legislativo"],
"Poder Judicial",
["justicia", " SCJ", "una unidad del Poder Judicial"],
["tribunal", "Tribunales", "un tribunal del poder judicial"],
["forense", "ITF", "un instituto del poder judicial"],
["juzgados", "Juzgados", "un juzgado del poder judicial"],
"Corte Electoral",
["corte_electoral", "Corte electoral", "una corte electoral"],
"Tribunal de lo Contencioso Administrativo",
["tribunal_contencioso_admnistrativo", "TCA", "un tribunal"],
"Tribunal de Cuentas",
["tribunal_cuentas", "TC", "un tribunal de cuentas"],
"Entes Autonomos",
["entes", "Entes", "un ente autonomo"],
["udelar", "UDELAR", "una universidad de la republica"],
["bcu", "BCU","un banco central"],
["bse", "BSE", "un banco de seguros"],
["brou","BROU", "un banco de la republica"],
["afe", "AFE", "una administracion de ferrocarriles del Estado"],
["inc" , "INC", "un instituto nacional de colonizacion"],
["bps", "BPS", "un banco de prevision social"],
["ute","UTE", "una administracion nacional usinas y telecomunicaciones electricas"],
["ancap","ANCAP", "una administracion nacional de alcohol, combustible y portland"],
["bhu", "BHU", "un banco hipotecario del Uruguay"],
["anep","ANEP", "una administraciona nacional de educacion publica"],
["codicen", "Codicen", "Un consejo de educacion central"],
["primaria", "Primaria","un consejo de educacion primaria"],
["secundaria", "Secundaria", "un consejo de educacion secundaria"],
["UTU", "UTU", "Una universidad del trabajo del Uruguay"],
"Servicios Descentralizados",
["ANP", "ANP", "Una administracion nacional de Puertos"],
["ASSE", "ASSE", "Un Administracion de Salud deL Estado"],
["INAU", "INAU", "Un instituto Nacional del Nino y el Adolescente"],
["ANTEL","ANTEL", "Una Administracion Nacional de Telecomunicaciones"],
["OSE","OSE", "Obras Sanitarias del Estado"],
["ANC", "Correos", "Una Administracion Nacional de Correos"],
["ANV", "Vivienda", "Administracion Nacional de Vivienda"],
"Gobiernos Departamentales",
["intendencia_montevideo", "Intendencia de Montevideo", "una intendencia"],
["intendencia_canelones", "Intendencia de Canelones", "una intendencia"],
["intendencia_ maldonado", "Intendencia de Maldonado", "una intendencia"],
["intendencia_rocha", "Intendencia de Rocha", "una intendencia"],
["intendencia_sanjose","Intendencia de San Jose", "una intendencia"],
["intendencia_flores","Intendencia de Flores", "una intendencia"],
["intendencia_florida","Intendencia de Florida", "una intendencia"],
["intendencia_cerrolargo","Intendencia de Cerro Largo", "una intendencia"],
["intendencia_lavalleja","Intendencia de Lavalleja", "una intendencia"],
["intendencia_colonia","Intendencia de Colonia", "una intendencia"],
["intendencia_paysandu","Intendencia de Paysandu", "una intendencia"],
["intendencia_salto","Intendencia de Salto", "una intendencia"],
["intendencia_artigas","Intendencia de Artigas", "una intendencia"],
["intendencia_rionegro","Intendencia de Rio Negro", "una intendencia"],
["intendencia_durazno","Intendencia de Durazno", "una intendencia"],
["intendencia_rivera_","Intendencia de Rivera", "una intendencia"],
["intendencia_tacuarembo", "Intendencia de Tacuarembo", "una intendencia"],
["intendencia_soriano","Intendencia de Soriano", "una intendencia"],
["intendencia_treintaytres","Intendencia de Treinta y Tres", "una intendencia"],
"Junta Departamental",
["junta_montevideo", " Junta de Montevideo", "una Junta Departamental"]
])
