PublicBodyCategories.add(:es, [
"Poder Ejecutivo",
["presidencia","Presidencia y organismos asociados", "una agencia de presidencia"],
["Agencias", "Presidencia y organismos asociados", "una agencia de presidencia"],
["Unidades","Presidencia y organismos asociados" "una unidad de presidencia"],
["Oficinas", "Presidencia y organismos asociados", "una oficina de presidencia"],
["Instituto", "Presidencia y organismos asociados", "Ministerios", "un instituto"],
["ministerio","Ministerios", "un ministerio"], 
["Direcciones", " Direcciones en los Ministerios", "una direccion de ministerio"], 
["Museos", " Museos que dependen de Ministerio", "un museo"],
["Embajadas", " Embajadas dependiente del Ministerio de Relaciones Exteriores", "Una Embajada Uruguaya"],
["Consulados", "Consulados dependientes del Ministerio de Relaciones Exteriores", "Un Consulado Uruguayo"],
"Poder Legislativo",
["Camara de Senadores", "Camara de Senadores", "Una Camara del Legislativo"],
["Camara de Diputados", "Camara de Diputados", "Una Camara del Legislativo"],
["Comision Administradora del Poder Legislativo", "Comision Administradora","Una Comision Administradora del Legislativo"]
"Poder Judicial",
["Suprema Corte de Justicia", " Suprema Corte de Justicia", "una unidad del Poder Judicial"],
["Tribunal de Apelaciones", "Tribunal de Apelaciones", "un tribunal del poder judicial"],
["Instituto tecnico forence", "Instituto Tecnico Forense", "un instituto del poder judicial"],
["Juzgados", "juzgados", "un juzgado del poder judicial"],
"Corte Electoral",
["Corte Electoral" "Corte electoral" "una corte electoral"],
"Tribunal de lo Contencioso Administrativo"
["Tribunal de los Contencioso Administrativo", "tribunal", "un tribunal"],
"Tribunal de Cuentas",
["Tribunal de Cuentas", "un tribunal", "un tribunal de cuentas"],
"Personas Publicas no Estatales"
["Personas Publicas No Estatales", "persona publica no estatal" "una persona publica no estatal"],
["Congreso de Intendentes","un congreso", "un congreso de intendentes"],
["Entes Autonomos"],
["UDELAR", "UDELAR", "una universidad de la republica"],
["BCU", "un entes autonomos","un banco central"], 
["BSE", "un entes autonomos, un banco de seguros"],
["BROU","un entes autonomos" "un banco de la republica"],
["AFE", "un entes autonomos", "una administracion de ferrocarriles del Estado"],
["INC" , "un entes autonomos", "un instituto nacional de colonizacion"],
["BPS", "un entes autonomos", "un banco de prevision social"],
["UTE","un entes autonomos", "una administracion nacional usinas y telecomunicaciones electricas"],
["ANCAP","un entes autonomos", "una administracion nacional de alcohol, combustible y portland"],
["BHU", "un entes autonomos", "un banco hipotecario del Uruguay"],
["ANEP","un entes autonomos", "una administraciona nacional de educacion publica"],
["CODICEN", "un entes autonomos", "Un consejo de educacion central"],
["Consejo de Ed. Primaria", "un entes autonomos","un consejo de educacion primaria"],
["Consejo de Ed. Secundaria", "un entes autonomos", "un consejo de educacion secundaria"],
["UTU", "un entes autonomos", "Una universidad del trabajo del Uruguay"],
"Servicios Descentralizados",
["ANP", "Servicios Descentralizados", "Una administracion nacional de Puertos"],
["ASSE", "Servicios Descentralizados", "Un Administracion de Salud deL Estado"],
["INAU", "Servicios Descentralizados", "Un instituto Nacional del Nino y el Adolescente"],
["ANTEL","Servicios Descentralizados", "Una Administracion Nacional de Telecomunicaciones"],
["OSE","Servicios Descentralizados", "Obras Sanitarias del Estado"],
["ANC", "Servicios Descentralizados", "Una Administracion Nacional de Correos"],
["ANV", "Servicios Descentralizados", "Administracion Nacional de Vivienda"],
"Gobiernos Departamentales",
["Intendencia de Montevideo","Gobiernos Departamentales", "una intendencia"],
["Intendencia de Canelones", "Gobiernos Departamentales", "una intendencia"],
["Intendencia de Maldonado", "Gobiernos Departamentales", "una intendencia"],
["Intendencia de Rocha", "Gobiernos Departamentales", "una intendencia"],
["Intendencia de San Jose","Gobiernos Departamentales", "una intendencia"],
["Intendencia de Flores","Gobiernos Departamentales", "una intendencia"],
["Intendencia de Florida","Gobiernos Departamentales", "una intendencia"],
["Intendencia de Cerro Largo","Gobiernos Departamentales", "una intendencia"],
["Intendencia de Lavalleja","Gobiernos Departamentales", "una intendencia"],
["Intendencia de Colonia","Gobiernos Departamentales", "una intendencia"],
["Intendencia de Paysandu","Gobiernos Departamentales", "una intendencia"],
["Intendencia de Salto","Gobiernos Departamentales", "una intendencia"],
["Intendencia de Artigas","Gobiernos Departamentales", "una intendencia"],
["Intendencia de Rio Negro","Gobiernos Departamentales", "una intendencia"],
["Intendencia de Durazno","Gobiernos Departamentales", "una intendencia"],
["Intendencia de Rivera","Gobiernos Departamentales", "una intendencia"],
["Intendencia de Tacuarembo", "Gobiernos Departamentales", "una intendencia"],
["Intendencia de Soriano","Gobiernos Departamentales", "una intendencia"],
["Intendencia de Treinta y Tres","Gobiernos Departamentales", "una intendencia"],
"Junta Departamental",
["Junta Departamental de Madonado","Gobiernos Departamentales", "una Junta Departamental"],
["Junta Departamental de Canelones", "Gobiernos Departamentales", "una Junta Departamental"],
["Junta Departamental de Maldonado", "Gobiernos Departamentales", "una Junta Departamental"],
["Junta Departamental de Rocha" "Gobiernos Departamentales", "una Junta Departamental"],
["Junta Departamental de San Jose","Gobiernos Departamentales", "una Junta Departamental"],
["Junta Departamental de Flores","Gobiernos Departamentales", "una Junta Departamental"],
["Junta Departamental de Florida","Gobiernos Departamentales", "una Junta Departamental"],
["Junta Departamental de Cerro Largo","Gobiernos Departamentales", "una Junta Departamental"],
["Junta Departamental de Lavalleja","Gobiernos Departamentales", "una Junta Departamental"],
["Junta Departamental de Colonia","Gobiernos Departamentales", "una Junta Departamental"],
["Junta Departamental de Paysandu","Gobiernos Departamentales", "una Junta Departamental"],
["Junta Departamental de Salto","Gobiernos Departamentales", "una Junta Departamental"],
["Junta Departamental de Artigas","Gobiernos Departamentales", "una Junta Departamental"],
["Junta Departamental de Rio Negro","Gobiernos Departamentales", "una Junta Departamental"],
["Junta Departamental de Durazno","Gobiernos Departamentales", "una Junta Departamental"],
["Junta Departamental de Rivera","Gobiernos Departamentales", "una Junta Departamental"],
["Junta Departamental deTacuarembo","Gobiernos Departamentales", "una Junta Departamental"],
["Junta Departamental de Soriano","Gobiernos Departamentales", "una Junta Departamental"],
["Junta Departamental de Treinta y Tres","Gobiernos Departamentales", "una Junta Departamental"],
"Alcaldia",
["junta_local","Junta Local Autonoma", "una Junta Local Autonoma"]
])
